version: "3.9"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/code
      - /code/node_modules
    ports: 
      - 3000:3000
networks:
  shared:
    name: old-node-test